### ISSUE TITLE
Simulate complete offline state

### ISSUE THREAD

**Issue by samselikoff** [craigshoemaker/offlinejs-simulate-ui#3]
This is a great library - thanks for working on it!

Any ideas how to simulate your app being completely offline? I'm finding this lib takes care of the UI, but I'd like to see how my app responds when things are actually offline - for example, when all `$.ajax` requests reject.

**Comment by craigshoemaker** [comment]
Thanks, @samselikoff!

Well the purpose of [offline.js](https://github.com/hubspot/offline) is simply to notify when the browser is offline and the simulator just forces offline.js to report as being in an offline state (whether or not there is a current connection). So neither of the modules are actually taking the browser offline so that other APIs are able to respond to a simulated or forced offline state. To do that sort of testing you will likely need to truly be offline.

Does that make sense?

**Comment by samselikoff** [comment]
Yep that makes sense. Thanks!
